### ISSUE TITLE
The NuGetPackage package did not load correctly (problem with packageSourceCredentials)

### ISSUE THREAD

**Issue by giggio** [NuGet/NuGet.VisualStudioExtension#5] opened 2015-02-25 21:46 UTC
The latest Nuget Package Manager for Visual Studio 2015, version 3.0.60223.242 is throwing whenever I request to Manage Packages.
This is the log from `%userprofile%\AppData\Roaming\Microsoft\VisualStudio\14.0\ActivityLog.xml`:

````xml
  <entry>
    <record>613</record>
    <time>2015/02/25 21:40:49.164</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Entering function CVsPackageInfo::HrInstantiatePackage</description>
    <guid>{5FCC8577-4FEB-4D04-AD72-D6C629B083CC}</guid>
  </entry>
  <entry>
    <record>614</record>
    <time>2015/02/25 21:40:49.164</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [NuGetPackage]</description>
    <guid>{5FCC8577-4FEB-4D04-AD72-D6C629B083CC}</guid>
  </entry>
  <entry>
    <record>615</record>
    <time>2015/02/25 21:40:49.166</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [NuGetPackage]</description>
    <guid>{5FCC8577-4FEB-4D04-AD72-D6C629B083CC}</guid>
    <hr>80131500</hr>
    <errorinfo>An exception was thrown while initializing part "NuGet.PackageManagement.VisualStudio.VSPackageRestoreManager".</errorinfo>
  </entry>
  <entry>
    <record>616</record>
    <time>2015/02/25 21:40:49.166</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [NuGetPackage]</description>
    <guid>{5FCC8577-4FEB-4D04-AD72-D6C629B083CC}</guid>
    <hr>80131500</hr>
    <errorinfo>An exception was thrown while initializing part "NuGet.PackageManagement.VisualStudio.VSPackageRestoreManager".</errorinfo>
  </entry>
````

**Comment by giggio** [comment] 2015-02-27 00:09
Ok, I have more info on this one. Once I deleted `~\AppData\Roaming\NuGet\Nuget.config` the error stopped.
This is what I had on the file, with company sensitive info removed:

````xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <apikeys>
    <add key="https://www.nuget.org" value="removed" />
    <add key="https://www.myget.org/F/somecompanyfeed-unstable/" value="removed" />
    <add key="https://www.myget.org/F/somecompanyfeed/" value="removed" />
    <add key="https://www.myget.org/F/somecompanyfeed-unstable/api/v2/package" value="removed" />
    <add key="https://www.myget.org/F/somecompanyfeed/api/v2/package" value="removed" />
    <add key="https://www.myget.org/F/somecompanyfeed-unstable/api/v2/" value="removed" />
    <add key="http://nuget.gw.symbolsource.org/Public/NuGet" value="removed" />
  </apikeys>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <activePackageSource>
    <add key="NuGet.org" value="https://nuget.org/api/v2/" />
  </activePackageSource>
  <packageSources>
    <add key="CodeCracker Unstable" value="https://www.myget.org/F/codecrackerbuild/api/v2" />
    <add key="https://www.nuget.org/api/v2/" value="https://www.nuget.org/api/v2/" />
    <add key="CompanyFeedUnstable" value="https://www.myget.org/F/somecompanyfeed-unstable/api/v2/" />
    <add key="NuGet.org" value="https://nuget.org/api/v2/" />
    <add key="AspNetVNextStable" value="https://www.myget.org/F/aspnetmaster/api/v2" />
    <add key="AspNetVNextUnstable" value="https://www.myget.org/F/aspnetvnext/api/v2" />
    <add key="CompanyFeed" value="https://www.myget.org/F/somecompanyfeed/api/v2/" />
  </packageSources>
  <disabledPackageSources>
    <add key="https://www.nuget.org/api/v2/" value="true" />
  </disabledPackageSources>
  <packageSourceCredentials>
    <CompanyFeedUnstable>
      <add key="Username" value="myusername" />
      <add key="Password" value="removed" />
    </CompanyFeedUnstable>
    <CompanyFeed>
      <add key="Username" value="myusername" />
      <add key="Password" value="removed" />
    </CompanyFeed>
  </packageSourceCredentials>
</configuration>
````

BTW, I just updated to the 3.0-beta2 announced [here](http://blog.nuget.org/20150226/nuget-3.0-beta2.html), and the problem persisted.

I have saved the original nuget.config file if you need to investigate further. Let me know.

**Comment by giggio** [comment] 2015-02-27 00:18
Digged a little bit more. The problem is the `packageSourceCredentials` xml element.
Any work around this issue with current 3.0-beta2 vsix?

**Comment by deepakaravindr** [comment] 2015-02-27 01:56
/cc @zhili1208 , @csharpfritz 

Root cause:

There is a bug in the reading of 'packageSourceCredentials' section in the xml. Due to which, if the section is present, and there are un-authenticated feeds, like in your case; it fails. Unfortunately, since loading of package sources fail. You are not able to launch 'Manage NuGet Packages'. If all of the feeds are authenticated, it will pass

Work-around:

There is a minor workaround. You can tweak the nuget.config, for example, as follows. What you are doing here, claiming that all the feeds are authenticated, but, leaving un-authenticated ones without a password (Note: I have renamed some of your package sources to be simple strings without spaces, so that, they can xml element names)

Problem is that this will work so long as you are not making changes to package sources. Once you make a change, NuGet will try to overwrite and remove the feed elements from 'packageSourceCredentials' which does not have any password in there. So, you will have to tweak NuGet.Config again. Let us know if the work-around does not work for you

````xml
  <packageSourceCredentials>
    <CodeCrackerUnstable>
      <add key="Username" value="myusername" />
    </CodeCrackerUnstable>
    <AspNetVNextUnstable>
      <add key="Username" value="myusername" />
    </AspNetVNextUnstable>
    <AspNetVNextStable>
      <add key="Username" value="myusername" />
    </AspNetVNextStable>
    <NuGet.org>
      <add key="Username" value="myusername" />
    </NuGet.org>
    <CompanyFeedUnstable>
      <add key="Username" value="myusername" />
      <add key="Password" value="removed" />
    </CompanyFeedUnstable>
    <CompanyFeed>
      <add key="Username" value="myusername" />
      <add key="Password" value="removed" />
    </CompanyFeed>
  </packageSourceCredentials>
````

Action item for us:
Will update this thread with more information with the action item for us. We know the fix, we will get back to you with when you will get the fix

**Comment by giggio** [comment] 2015-02-27 15:40
@deepakaravindr Ok, I have tried the workaround, it does not work. The Tools/Options in VS is not able to show the packages, and the Manage Nuget Packages windows for project also does not work.

**Comment by deepakaravindr** [comment] 2015-02-27 21:42
@giggio . I see what the problem is. Looks like my tweak suggestion did not cover the default 'api.nuget.org' feed and the machine-level 'Microsoft and .NET' feed. I will help you through this.. I have a working work-around, so, I am sure I can unblock you. Thanks for your patience!

Try the following steps and let me know

1. Handling the 'Microsoft and .NET' feed. If you do not care for 'Microsoft and .NET' curated feed at all; Go to "C:\ProgramData\NuGet\Config\VisualStudio\14.0", Rename 'Microsoft.VisualStudio.Config' to 'Microsoft.VisualStudio.config.txt'. And, you are good. If you want this feed; Check out the 'Additional information section' at the end
2.  Please try the following config file. 
     1. Note that the password is the encrypted value of "removed". You can simply replace this with the actual encrypted password from you original NuGet.Config file. Note that using a plain text password will not work, since, nuget.config reader will try to decrypt the password string. Check out http://docs.nuget.org/consume/NuGet-Config-Settings for more info
     2. Also, note that 'api.nuget.org' feed is also added to 'packageSourceCredentials' section. This is needed, since it is always added by default if it is not present

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <apikeys>
    <add key="https://www.nuget.org" value="removed" />
    <add key="https://www.myget.org/F/somecompanyfeed-unstable/" value="removed" />
    <add key="https://www.myget.org/F/somecompanyfeed/" value="removed" />
    <add key="https://www.myget.org/F/somecompanyfeed-unstable/api/v2/package" value="removed" />
    <add key="https://www.myget.org/F/somecompanyfeed/api/v2/package" value="removed" />
    <add key="https://www.myget.org/F/somecompanyfeed-unstable/api/v2/" value="removed" />
    <add key="http://nuget.gw.symbolsource.org/Public/NuGet" value="removed" />
  </apikeys>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
    <add key="CodeCrackerUnstable" value="https://www.myget.org/F/codecrackerbuild/api/v2" />
    <add key="CompanyFeedUnstable" value="https://www.myget.org/F/somecompanyfeed-unstable/api/v2/" />
    <add key="NuGet.org" value="https://nuget.org/api/v2/" />
    <add key="AspNetVNextStable" value="https://www.myget.org/F/aspnetmaster/api/v2" />
    <add key="AspNetVNextUnstable" value="https://www.myget.org/F/aspnetvnext/api/v2" />
    <add key="CompanyFeed" value="https://www.myget.org/F/somecompanyfeed/api/v2/" />
  </packageSources>
  <packageSourceCredentials>
    <api.nuget.org>
      <add key="Username" value="myusername" />
    </api.nuget.org>
    <CodeCrackerUnstable>
      <add key="Username" value="myusername" />
    </CodeCrackerUnstable>
    <CompanyFeedUnstable>
      <add key="Username" value="myusername" />
      <add key="ClearTextPassword" value="AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAB3Hdj7fL7kqE6Q4Jpkpm6gAAAAACAAAAAAADZgAAwAAAABAAAABkYoY

+keGRrxWgKs0mNrWRAAAAAASAAACgAAAAEAAAAA0wLkJpwOFeTAISGn1TQcQIAAAA0YY2br/kxe8UAAAAD3x91oO70Q7+ed4PeVjRR1iMqG4=" />
    </CompanyFeedUnstable>
    <NuGet.org>
      <add key="Username" value="myusername" />
    </NuGet.org>
    <AspNetVNextUnstable>
      <add key="Username" value="myusername" />
    </AspNetVNextUnstable>
    <AspNetVNextStable>
      <add key="Username" value="myusername" />
    </AspNetVNextStable>
    <CompanyFeed>
      <add key="Username" value="myusername" />
      <add key="ClearTextPassword" value="AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAB3Hdj7fL7kqE6Q4Jpkpm6gAAAAACAAAAAAADZgAAwAAAABAAAABkYoY

+keGRrxWgKs0mNrWRAAAAAASAAACgAAAAEAAAAA0wLkJpwOFeTAISGn1TQcQIAAAA0YY2br/kxe8UAAAAD3x91oO70Q7+ed4PeVjRR1iMqG4=" />
    </CompanyFeed>
  </packageSourceCredentials>
  <activePackageSource>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </activePackageSource>
</configuration>
```

Additional information section:
Check out the following only if the above does not work for you. Otherwise, it might become information overload. Sorry about that :(

1. Please double-check that the feed names you have used and entered in the 'packageSourceCredentials' are valid xml element names. For example, 'Microsoft and .NET' is not valid since there are spaces in this name. Also, a http url is not a valid name, like you have used in your original config file. Note that I will file a bug on NuGet to never allow invalid xml element names as feed names or fix the schema to not use feed names as xml element names
2. If there are other NuGet.Config files in the solution directory or solutiondirectory/.nuget folder or anywhere in the ancestor folder of the solution directory, apply the tweak there too
3. This is if you want to use 'Microsoft and .NET' feed. Open 'C:\ProgramData\NuGet\Config\VisualStudio\14.0\Microsoft.VisualStudio.config'. Edit the feed name 'Microsoft and .NET' to a valid xml element name like 'Microsoft_and_.NET'. Add an entry like the following to 'packageSourceCredentials' section

```xml
    <Microsoft_and_.NET>
      <add key="Username" value="myusername" />
    </Microsoft_and_.NET>
```

**Comment by CZEMacLeod** [comment] 2015-03-02 15:48
In case anyone has feeds setup with spaces; or for the default Microsoft and .NET feed. You can replace a space with \_x0020\_ in the packageSoruceCredentials section:

	<Microsoft_x0020_and_x0020_.NET>
		<add key="Username" value="myusername"/>
	</Microsoft_x0020_and_x0020_.NET>

**Comment by deepakaravindr** [comment] 2015-03-02 19:56
@CZEMacLeod , Thanks for the easier workaround!

@giggio , Did the work-around work for you? Let us know. Thanks!

**Comment by giggio** [comment] 2015-03-03 11:14
@deepakaravindr No, it did not. I am working on an ASP.NET vNext project, and it fails on VS. And the Tools/Options/Nuget property pages don't load. I had disabled the curated feed, still, it failed.
We have setup a local feed inside our network until this is fixed, which hopefully won't be long.

**Comment by deepakaravindr** [comment] 2015-03-04 00:51
@giggio, Thanks for trying! Not sure why the work-around did not work... Nevertheless, I will update this issue once the fix is available for public

**Comment by deepakaravindr** [comment] 2015-03-12 08:05
Was fixed with NuGet/NuGet.Configuration@86bff60

**Comment by deepakaravindr** [comment] 2015-03-12 08:05
Will close it once the fix is available to public

**Comment by smithkl42** [comment] 2015-03-31 16:13
@deepakaravindr - Any idea when the fix will be available? I'd like to be using VS2015, but can't because of this. (None of the workarounds I've tried have worked.)

**Comment by CZEMacLeod** [comment] 2015-03-31 17:31
@deepakaravindr  I found it crashing too often, and having to rebuild/replace the .config file whenever I changed the default feed was making it unusable - I also had to revert to the original 2015 nuget package manager.

**Comment by deepakaravindr** [comment] 2015-03-31 18:23
@giggio, @CZEMacLeod , @smithkl42, Please note that this fix should be available in VS 2015 RC. As you already know, the issue Was fixed with NuGet/NuGet.Configuration@86bff60. 

We are closing this issue. For filing more issues, please use https://github.com/NuGet/Home/issues.
We will be disabling issues from this repository.

**Closed by deepakaravindr** 2015-03-31 18:23 UTC
